# Generated by Django 5.0.6 on 2024-05-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scraper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255)),
                ("ad_title", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image_urls", models.URLField(max_length=255, unique=True)),
                ("publish_date", models.DateTimeField(auto_now_add=True)),
                ("price", models.IntegerField()),
                ("quantity_rooms", models.IntegerField()),
                ("area", models.IntegerField()),
            ],
            options={
                "ordering": ["ad_title"],
            },
        ),
    ]
